name: Actions Pipeline

on:
  push:
    branches:
      - melnychuk
  pull_request:
    branches:
      - melnychuk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build code
        run: |
          echo "Building the project..."
          # Replace this with actual build commands

